### ISSUE TITLE
怎么用呀,在pycharm里运行吗?

### ISSUE THREAD

**Issue by wiiii** [facert/tumblr_spider#5]
D:\Develop\mzitu\venv\Scripts\python.exe D:/Develop/PythonSpace/tumblr_spider/tumblr.py
usage: python tumblr.py username

Process finished with exit code 0

**Comment by xiaoxiaofenyge** [comment]
在pycharm里，Run... -->Edit Configurations -->Parameters:填入username
![image](https://user-images.githubusercontent.com/37503457/41235158-b1d9391e-6dc0-11e8-8aa2-aa88006521c0.png)
![image](https://user-images.githubusercontent.com/37503457/41235178-c039fa98-6dc0-11e8-896b-4c3a0da7fc88.png)
![image](https://user-images.githubusercontent.com/37503457/41235199-d268d978-6dc0-11e8-8eb8-a602f4f36522.png)

**Comment by xiaoxiaofenyge** [comment]
在Pycharm里，Run... -->Edit Configurations... --> Parameters: 填入username
![image](https://user-images.githubusercontent.com/37503457/41235382-47b0355a-6dc1-11e8-81ab-c83f1ec933f7.png)
![image](https://user-images.githubusercontent.com/37503457/41235409-52fe6cba-6dc1-11e8-8d0d-a2593941768d.png)
![image](https://user-images.githubusercontent.com/37503457/41235352-3bb65824-6dc1-11e8-804f-fdffd97ff06a.png)
